image: alpine/edge
oauth: pages.sr.ht/PAGES:RW
packages:
  - hut
  - npm
  - rsync
  - typst
environment:
  site: mzhang.io
secrets:
  - 0b26b413-7901-41c3-a4e2-3c752228ffcb
sources:
  - https://git.sr.ht/~mzhang/blog
tasks:
  - install: |
      sudo npm install -g pnpm
  - build: |
      cd blog
      pnpm install
      pnpm run build
      # hugo --buildDrafts --minify --baseURL https://mzhang.io
  - upload: |
      cd blog/dist
      tar -cvz . > ../site.tar.gz
      cd ..
      hut pages publish -d $site site.tar.gz
      # echo "mzhang.io ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBzBZ+QmM4EO3Fwc1ZcvWV2IY9VF04T0H9brorGj9Udp" >> ~/.ssh/known_hosts
      # rsync -azvrP dist/ sourcehutBuilds@mzhang.io:/mnt/storage/svcdata/blog-public
