image: archlinux
packages:
  - hugo
  - rsync
secrets:
  - 0b26b413-7901-41c3-a4e2-3c752228ffcb
sources:
  - https://git.sr.ht/~mzhang/blog
tasks:
  - build: |
      cd blog
      hugo --baseURL https://mzhang.io
  - upload: |
      echo "mzhang.io ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBzBZ+QmM4EO3Fwc1ZcvWV2IY9VF04T0H9brorGj9Udp" >> ~/.ssh/known_hosts
      rsync -azvrP public/ sourcehutBuilds@mzhang.io:/mnt/storage/svcdata/blog-public
