steps:
  build:
    image: git.mzhang.io/michael/blog-docker-builder:l3kh5sx46zqszsbr1ghvvdyp0zl8gl9m
    environment:
      - ASTRO_TELEMETRY_DISABLED=1
    commands:
      - mkdir /tmp
      - rm -rf node_modules
      - npm i -g pnpm@9.4.0
      - npx pnpm install --frozen-lockfile
      - npx pnpm run build
    when:
      - event: push

  deploy:
    image: git.mzhang.io/michael/blog-docker-builder:l3kh5sx46zqszsbr1ghvvdyp0zl8gl9m
    commands:
      - aws s3 sync ./dist/ s3://mzhang-io-website/
    secrets:
      - AWS_ACCESS_KEY_ID
      - AWS_DEFAULT_REGION
      - AWS_ENDPOINT_URL
      - AWS_SECRET_ACCESS_KEY
    when:
      - branch: master
        event: push
