steps:
  build:
    # image: node:20
    image: oven/bun:1
    commands:
    #   - npm install -g pnpm
    #   - pnpm install
    #   - pnpm run build
      - bun install --frozen-lockfile
      - bun run build
    when:
      - event: push

  deploy:
    image: alpine
    commands:
      - apk add rsync openssh
      - echo "$${SSH_SECRET_KEY}" > SSH_SECRET_KEY
      - chmod 600 SSH_SECRET_KEY
      - mkdir -p ~/.ssh
      - echo "mzhang.io ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIO+RKFYjD8UjqhfOHFHNyijkbGzC4fJEIIhrBwHj+FsQ" >> ~/.ssh/known_hosts
      - rsync -azrP -e "ssh -i SSH_SECRET_KEY" dist/ blogDeploy@mzhang.io:/home/blogDeploy/public
    secrets: [SSH_SECRET_KEY]
    when:
      - branch: master
        event: push
