pipeline:
  build:
    image: klakegg/hugo
    commands:
      - ls -al
      - pwd
      - hugo --minify --baseURL https://mzhang.io

  deploy:
    image: alpine
    commands:
      - ls -al
      - pwd
      - echo "$SSH_SECRET_KEY" > SSH_SECRET_KEY
      - echo "mzhang.io ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBzBZ+QmM4EO3Fwc1ZcvWV2IY9VF04T0H9brorGj9Udp" >> ~/.ssh/known_hosts
      - rsync -azvrP -e "ssh -i SSH_SECRET_KEY" public/ sourcehutBuilds@mzhang.io:/mnt/storage/svcdata/blog-public
    when:
      branch: master
