pipeline:
  build:
    image: klakegg/hugo:ext-pandoc-ci
    commands:
      - hugo --minify --baseURL https://mzhang.io

  deploy:
    image: alpine
    commands:
      - apk add rsync openssh
      - echo "$${SSH_SECRET_KEY}" > SSH_SECRET_KEY
      - chmod 600 SSH_SECRET_KEY
      - mkdir -p ~/.ssh
      - echo "mzhang.io ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBzBZ+QmM4EO3Fwc1ZcvWV2IY9VF04T0H9brorGj9Udp" >> ~/.ssh/known_hosts
      - rsync -azvrP -e "ssh -i SSH_SECRET_KEY" public/ sourcehutBuilds@mzhang.io:/mnt/storage/svcdata/blog-public
    secrets: [ SSH_SECRET_KEY ]
    when:
      branch: master
