pipeline:
  build:
    image: node:20
    commands:
      #   - cd /tmp
      #   - rm -rf astro
      #   - git clone https://git.mzhang.io/michael/astro --depth 1
      #   - cd astro
      #   - pnpm install
      #   - pnpm run build
      #   - cd /woodpecker/src/git.mzhang.io/michael/blog
      - pnpm install
      #   - pnpm link /tmp/astro/packages/astro
      #   - pnpm link /tmp/astro/packages/markdown/remark
      - pnpm run build

  deploy:
    image: alpine
    commands:
      - apk add rsync openssh
      - echo "$${SSH_SECRET_KEY}" > SSH_SECRET_KEY
      - chmod 600 SSH_SECRET_KEY
      - mkdir -p ~/.ssh
      - echo "mzhang.io ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBzBZ+QmM4EO3Fwc1ZcvWV2IY9VF04T0H9brorGj9Udp" >> ~/.ssh/known_hosts
      - rsync -azrP -e "ssh -i SSH_SECRET_KEY" dist/ sourcehutBuilds@mzhang.io:/mnt/storage/svcdata/blog-public
    secrets: [SSH_SECRET_KEY]
    when:
      branch: master
