baseURL = "http://example.org/"
languageCode = "en-us"
title = "michael's blog"
enableGitInfo = true

[taxonomies]
tag = "tags"
language = "languages"

[markup.tableOfContents]
endLevel = 4
ordered = true
startLevel = 2

[markup.goldmark.renderer]
unsafe = true
