title = "michael's blog"
base_url = "https://mzhang.me"

compile_sass = true
highlight_code = true
generate_rss = true

[extra]
nav_links = [
    { url = "/pages/about", text = "about" },
    { url = "https://git.mzhang.me/", text = "projects" },
]
