baseURL = "http://example.org/"
languageCode = "en-us"
title = "Michael's Blog"
enableGitInfo = true

[taxonomies]
tag = "tags"
language = "languages"

[markup.tableOfContents]
endLevel = 4
ordered = false
startLevel = 2

[markup.goldmark.renderer]
unsafe = true
