baseURL = "http://example.org/"
languageCode = "en-us"
title = "michael's blog"
enableGitInfo = true

[taxonomies]
tag = "tags"
language = "languages"

[markup.tableOfContents]
endLevel = 4
ordered = true
startLevel = 2

[mediaTypes."application/activitypub"]
suffixes = ["json"]

[outputs]
section = ["HTML", "ActivityPub"]

[outputFormats.ActivityPub]
baseName = "ActivityPub"
mediaType = "application/activitypub"
isPlainText = true

