steps:
  build:
    image: git.mzhang.io/michael/blog-docker-builder:kxawk2x5isy1sfn4faqz0c3vv2j2106r
    environment:
      - ASTRO_TELEMETRY_DISABLED=1
    commands:
      - mkdir /tmp
      - rm -rf node_modules
      - npm ci # Man @ sharp installation issues... (https://ci.mzhang.io/repos/1/pipeline/124/3)
      - bun run build
    when:
      - event: push

  deploy:
    image: git.mzhang.io/michael/blog-docker-builder:kxawk2x5isy1sfn4faqz0c3vv2j2106r
    commands:
      - mc alias set $AWS_DEFAULT_REGION $AWS_ENDPOINT_URL $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY --api S3v4
      - mc mirror --overwrite ./dist/ $AWS_DEFAULT_REGION/mzhang-io-website/
    secrets:
      - AWS_ACCESS_KEY_ID
      - AWS_DEFAULT_REGION
      - AWS_ENDPOINT_URL
      - AWS_SECRET_ACCESS_KEY
    when:
      - branch: master
        event: push
